version: '3'
services:
  electric-flow:
    image: "electricflow/efserver:latest-windowsservercore"
    ports:
    - "8000:8000"
    - "8443:8443"
    - "443:443"
    - "80:80"
    container_name: "efserver"
    hostname: "efserver"
    tty: true